# Generated by Django 4.0.2 on 2022-02-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'memale')], max_length=7),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_status',
            field=models.CharField(choices=[('Published', 'published'), ('Unpublished', 'unpublished'), ('Unknown', 'unknown')], max_length=12),
        ),
    ]
